//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public int id { get; set; }
        public string tipo { get; set; }
        public Nullable<int> idEmpleado { get; set; }
        public string dptOrigen { get; set; }
        public string dptDestino { get; set; }
        public string secuencia { get; set; }
        public string fecha { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
